# Generated by Django 4.1.3 on 2022-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
