# Generated by Django 4.1.3 on 2022-11-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_total_amount_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Закази'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказі', 'verbose_name_plural': 'Товари в заказі'},
        ),
    ]
